export const MOVIES_REQUEST= "MOVIES_REQUEST";
export const MOVIES_SUCCESS = "MOVIES_SUCCESS";
export const MOVIES_FAILURE = "MOVIES_FAILURE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SINGLE_MOVIES_REQUEST= "SINGLE_MOVIES_REQUEST";
export const SINGLE_MOVIES_SUCCESS = "SINGLE_MOVIES_SUCCESS";
export const SINGLE_MOVIES_FAILURE = "SINGLE_MOVIES_FAILURE";
